WILL BE DONE
- "'s" like structures might left as meaningless single "s"
- after stop word delete empty phrases might occur
- Porter Stemming and Lemmatizing (both available in NLTK) might be used to treat "messages", "message", and "messaging" as the same word

DONE
- all phrases are lowered
- punctuations in phrases are erased
- empty phrase rows returned to NA then erased
- stop words (nltk library pre created stop words list is used) in phrases are erased

In [57]:
import pandas as pd
df=pd.read_csv('data/train.csv',sep="\t")
df.head()

,PhraseId,SentenceId,Phrase,Sentiment
0,1,1,A series of escapades demonstrating the adage ...,1
1,2,1,A series of escapades demonstrating the adage ...,2
2,3,1,A series,2
3,4,1,A,2
4,5,1,series,2

In [58]:
df.Sentiment.describe()

count    156060.000000
mean          2.063578
std           0.893832
min           0.000000
25%           2.000000
50%           2.000000
75%           3.000000
max           4.000000
Name: Sentiment, dtype: float64

In [59]:
df.dtypes

PhraseId       int64
SentenceId     int64
Phrase        object
Sentiment      int64
dtype: object

In [60]:
df.Phrase=df.Phrase.str.lower()
df.head()

,PhraseId,SentenceId,Phrase,Sentiment
0,1,1,a series of escapades demonstrating the adage ...,1
1,2,1,a series of escapades demonstrating the adage ...,2
2,3,1,a series,2
3,4,1,a,2
4,5,1,series,2

In [61]:
df.Phrase = df.Phrase.str.replace('[^\w\s]','')
df.head()

,PhraseId,SentenceId,Phrase,Sentiment
0,1,1,a series of escapades demonstrating the adage ...,1
1,2,1,a series of escapades demonstrating the adage ...,2
2,3,1,a series,2
3,4,1,a,2
4,5,1,series,2

In [62]:
singleMask = df.Phrase.str.match(r'\A[\w-]+\Z')
singleMask[0:5]

0    False
1    False
2    False
3     True
4     True
Name: Phrase, dtype: bool

In [63]:
for x in range(0,singleMask.size):
    if singleMask[x]==True:
        singleMask[x]=False
    else:
        singleMask[x]=True
singleMask[0:5]

0     True
1     True
2     True
3    False
4    False
Name: Phrase, dtype: bool

In [64]:
df=df[singleMask]
df.head(n=40)

,PhraseId,SentenceId,Phrase,Sentiment
0,1,1,a series of escapades demonstrating the adage ...,1
1,2,1,a series of escapades demonstrating the adage ...,2
2,3,1,a series,2
5,6,1,of escapades demonstrating the adage that what...,2
7,8,1,escapades demonstrating the adage that what is...,2
9,10,1,demonstrating the adage that what is good for ...,2
10,11,1,demonstrating the adage,2
12,13,1,the adage,2
15,16,1,that what is good for the goose,2
17,18,1,what is good for the goose,2
19,20,1,is good for the goose,2
21,22,1,good for the goose,3
23,24,1,for the goose,2
25,26,1,the goose,2
27,28,1,is also good for the gander some of which occ...,2
28,29,1,is also good for the gander some of which occ...,2
29,30,1,is also,2
31,32,1,good for the gander some of which occasionall...,2
32,33,1,for the gander some of which occasionally amu...,2
33,34,1,the gander some of which occasionally amuses ...,1
34,35,1,the gander,2
35,36,1,the gander,2
37,38,1,,2
38,39,1,some of which occasionally amuses but none of ...,2
39,40,1,some of which,2
41,42,1,of which,2
43,44,1,occasionally amuses but none of which amounts ...,2
45,46,1,amuses but none of which amounts to much of a ...,2
47,48,1,but none of which amounts to much of a story,1
49,50,1,none of which amounts to much of a story,1
51,52,1,of which amounts to much of a story,2
52,53,1,which amounts to much of a story,2
53,54,1,amounts to much of a story,2
55,56,1,to much of a story,2
57,58,1,much of a story,2
59,60,1,of a story,2
60,61,1,a story,2
62,63,1,,2
63,64,2,this quiet introspective and entertaining ind...,4
64,65,2,this quiet introspective and entertaining ind...,3

In [65]:
import numpy as np
def change_nan(x):
    if pd.isnull(x):
        return np.nan
    
    if len(x) == 0:
        return np.nan
    return x

In [66]:
df['Phrase'] = df.Phrase.map(change_nan)
df=df.dropna()
df.head(n=40)

,PhraseId,SentenceId,Phrase,Sentiment
0,1,1,a series of escapades demonstrating the adage ...,1
1,2,1,a series of escapades demonstrating the adage ...,2
2,3,1,a series,2
5,6,1,of escapades demonstrating the adage that what...,2
7,8,1,escapades demonstrating the adage that what is...,2
9,10,1,demonstrating the adage that what is good for ...,2
10,11,1,demonstrating the adage,2
12,13,1,the adage,2
15,16,1,that what is good for the goose,2
17,18,1,what is good for the goose,2
19,20,1,is good for the goose,2
21,22,1,good for the goose,3
23,24,1,for the goose,2
25,26,1,the goose,2
27,28,1,is also good for the gander some of which occ...,2
28,29,1,is also good for the gander some of which occ...,2
29,30,1,is also,2
31,32,1,good for the gander some of which occasionall...,2
32,33,1,for the gander some of which occasionally amu...,2
33,34,1,the gander some of which occasionally amuses ...,1
34,35,1,the gander,2
35,36,1,the gander,2
38,39,1,some of which occasionally amuses but none of ...,2
39,40,1,some of which,2
41,42,1,of which,2
43,44,1,occasionally amuses but none of which amounts ...,2
45,46,1,amuses but none of which amounts to much of a ...,2
47,48,1,but none of which amounts to much of a story,1
49,50,1,none of which amounts to much of a story,1
51,52,1,of which amounts to much of a story,2
52,53,1,which amounts to much of a story,2
53,54,1,amounts to much of a story,2
55,56,1,to much of a story,2
57,58,1,much of a story,2
59,60,1,of a story,2
60,61,1,a story,2
63,64,2,this quiet introspective and entertaining ind...,4
64,65,2,this quiet introspective and entertaining ind...,3
66,67,2,quiet introspective and entertaining independent,4
67,68,2,quiet introspective and entertaining,3

In [67]:
from nltk.corpus import stopwords
stopwords_set = set(stopwords.words('english'))

In [68]:
def stop_erase(x):
    proper_words = []
    words = x.split()
    for word in words:
        if not word in stopwords_set:
           proper_words.append(word)
        
    return " ".join(proper_words)

In [69]:
df.Phrase=df.Phrase.map(stop_erase)

In [70]:
df.head(n=30)

,PhraseId,SentenceId,Phrase,Sentiment
0,1,1,series escapades demonstrating adage good goos...,1
1,2,1,series escapades demonstrating adage good goose,2
2,3,1,series,2
5,6,1,escapades demonstrating adage good goose,2
7,8,1,escapades demonstrating adage good goose,2
9,10,1,demonstrating adage good goose,2
10,11,1,demonstrating adage,2
12,13,1,adage,2
15,16,1,good goose,2
17,18,1,good goose,2
19,20,1,good goose,2
21,22,1,good goose,3
23,24,1,goose,2
25,26,1,goose,2
27,28,1,also good gander occasionally amuses none amou...,2
28,29,1,also good gander occasionally amuses none amou...,2
29,30,1,also,2
31,32,1,good gander occasionally amuses none amounts m...,2
32,33,1,gander occasionally amuses none amounts much s...,2
33,34,1,gander occasionally amuses none amounts much s...,1
34,35,1,gander,2
35,36,1,gander,2
38,39,1,occasionally amuses none amounts much story,2
39,40,1,,2
41,42,1,,2
43,44,1,occasionally amuses none amounts much story,2
45,46,1,amuses none amounts much story,2
47,48,1,none amounts much story,1
49,50,1,none amounts much story,1
51,52,1,amounts much story,2

In [71]:
df['Phrase'] = df.Phrase.map(change_nan)
df=df.dropna()
df.head(n=40)

,PhraseId,SentenceId,Phrase,Sentiment
0,1,1,series escapades demonstrating adage good goos...,1
1,2,1,series escapades demonstrating adage good goose,2
2,3,1,series,2
5,6,1,escapades demonstrating adage good goose,2
7,8,1,escapades demonstrating adage good goose,2
9,10,1,demonstrating adage good goose,2
10,11,1,demonstrating adage,2
12,13,1,adage,2
15,16,1,good goose,2
17,18,1,good goose,2
19,20,1,good goose,2
21,22,1,good goose,3
23,24,1,goose,2
25,26,1,goose,2
27,28,1,also good gander occasionally amuses none amou...,2
28,29,1,also good gander occasionally amuses none amou...,2
29,30,1,also,2
31,32,1,good gander occasionally amuses none amounts m...,2
32,33,1,gander occasionally amuses none amounts much s...,2
33,34,1,gander occasionally amuses none amounts much s...,1
34,35,1,gander,2
35,36,1,gander,2
38,39,1,occasionally amuses none amounts much story,2
43,44,1,occasionally amuses none amounts much story,2
45,46,1,amuses none amounts much story,2
47,48,1,none amounts much story,1
49,50,1,none amounts much story,1
51,52,1,amounts much story,2
52,53,1,amounts much story,2
53,54,1,amounts much story,2
55,56,1,much story,2
57,58,1,much story,2
59,60,1,story,2
60,61,1,story,2
63,64,2,quiet introspective entertaining independent w...,4
64,65,2,quiet introspective entertaining independent,3
66,67,2,quiet introspective entertaining independent,4
67,68,2,quiet introspective entertaining,3
69,70,2,introspective entertaining,3
70,71,2,introspective entertaining,3

In [72]:
df.dtypes

PhraseId       int64
SentenceId     int64
Phrase        object
Sentiment      int64
dtype: object

In [73]:
df = df.reset_index(drop=True)
df.head(n=30)

,PhraseId,SentenceId,Phrase,Sentiment
0,1,1,series escapades demonstrating adage good goos...,1
1,2,1,series escapades demonstrating adage good goose,2
2,3,1,series,2
3,6,1,escapades demonstrating adage good goose,2
4,8,1,escapades demonstrating adage good goose,2
5,10,1,demonstrating adage good goose,2
6,11,1,demonstrating adage,2
7,13,1,adage,2
8,16,1,good goose,2
9,18,1,good goose,2
10,20,1,good goose,2
11,22,1,good goose,3
12,24,1,goose,2
13,26,1,goose,2
14,28,1,also good gander occasionally amuses none amou...,2
15,29,1,also good gander occasionally amuses none amou...,2
16,30,1,also,2
17,32,1,good gander occasionally amuses none amounts m...,2
18,33,1,gander occasionally amuses none amounts much s...,2
19,34,1,gander occasionally amuses none amounts much s...,1
20,35,1,gander,2
21,36,1,gander,2
22,39,1,occasionally amuses none amounts much story,2
23,44,1,occasionally amuses none amounts much story,2
24,46,1,amuses none amounts much story,2
25,48,1,none amounts much story,1
26,50,1,none amounts much story,1
27,52,1,amounts much story,2
28,53,1,amounts much story,2
29,54,1,amounts much story,2

In [74]:
df.to_csv("data/cleaneddf.csv", sep='\t')